# -*- coding: utf-8 -*-
"""dataframe_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_2joHgECoOm7gtkas95rH3gC_EzMLYf
"""

import pandas as pd

d = {'col1':[1,2,3,4,7],'col2':[4,5,6,9,5],'col3':[7,8,12,1,11]}
data_frame = pd.DataFrame(data=d)
print(data_frame)

# count the number of colum
count_col = data_frame.shape[1]
print(count_col)

# count the number of rows
count_row = data_frame.shape[0]
print(count_row)


Average_pulse_max = max(80, 85, 90, 95, 100, 105, 110, 115, 120, 125)

print ('max value without pandas library is %d',Average_pulse_max)


import numpy as np
Calorie_burnage = [240, 250, 260, 270, 280, 290, 300, 310, 320, 330]
print('average calorie burn %d',np.mean(Calorie_burnage))
print('max calorie burn %d',np.max(Calorie_burnage))
print('Min calorie burn %d',np.min(Calorie_burnage))

# upload file from computer to google drive
# from google.colab import files
# uploaded = files.upload()
# import io
# df = pd.read_csv(io.BytesIO(uploaded['healthcare_dataset.csv']))
# print(df)


import pandas as pd
from google.colab import files

#health_data = pd.read_csv('data.csv',header=0,sep=",")
from google.colab import drive
drive.mount(mountpoint='/content/gdrive')
health_data = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/healthcare_dataset.csv',header=0,sep=",")
print('\nHealth Data info() function to list the data types within our data set: \n')
print(health_data.info())
print('Health Data Head Information we use the head() function to only show the top 5rows\n')
print(health_data.head())
#print(health_data.describe()) # We can use the describe() function in Python to summarize (count, max, min, stdander deviation) data:

print('We can use the astype() function to convert the data into float64, or int or datetime64\n')
health_data['Date of Admission'] = health_data['Date of Admission'].astype('datetime64[ns]')
print(health_data.info())


print('Remove Blank Data row \n')
health_data.dropna(axis=0,inplace=True)
print(health_data)