# -*- coding: utf-8 -*-
"""lib version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeZlBteX3QY5TWn-C1FKs2BV9Q-6dLPH

# **This is the first phase**
"""

print(" ********** I am Rashedul Hoque, Practice Project of Data Science  ********** \n")
import pandas as pd
print("2 Pandas version is "+pd.__version__)
import numpy as np
print("3 Numpy version is "+np.__version__)
import matplotlib as plt
print("4 Matplotlib version is "+plt.__version__)
import sklearn as sk
print("5 Scikit-learn version is "+sk.__version__)
import seaborn as sns
print("6 Seaborn version is "+sns.__version__)
import scipy as sp
print("7 Scipy version is "+sp.__version__)
import statsmodels as sm
print("8 Statsmodels version is "+sm.__version__)
import tensorflow as tf
print("9 Tensorflow version is "+tf.__version__)
import keras
print("10 Keras version is "+keras.__version__)
import torch
print("11 PyTorch version is "+torch.__version__)

print('1 math ==============================================')

dic = {'roll':[10,20,30,15,1,8,9,6,5,2,5]}
dic['roll']

import math

print("its math library {}".format(type(math)))
print(dir(math))
print("math pi variable is {} ".format(math.pi),"\n doc is {}".format(math.__doc__),"\n doc is {}".format(math.__doc__.count),"\n loader  is {}".format(math.__loader__),
      "\n Log function is ",math.log(10,2),help(math.log))


import math as mt
print('\n degree function is ', mt.degrees, mt.degrees(math.pi/2))

# import * makes all the module's variables directly accessible to you (without any dotted prefix). Bad news: some purists might grumble at you for doing this. Worse: they kind of have a point.
from math import *
print('\n with out dot use variabl',pi)

print('2  numpy ==============================================')
import numpy
print("\n 1 type of numpy ",type(numpy),"\n 2 numpy dir demo value from index -3 to 0 ",dir(numpy.random)[-3:+5])

